# Generated by Django 5.2.5 on 2025-08-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('finger_detected', models.BooleanField(default=False)),
                ('heart_rate', models.IntegerField()),
                ('o2_level', models.IntegerField(blank=True, null=True)),
                ('ir_value', models.IntegerField(blank=True, null=True)),
                ('signal_quality', models.CharField(blank=True, max_length=20, null=True)),
                ('test_counter', models.IntegerField(blank=True, null=True)),
                ('test_mode', models.BooleanField(default=False)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
